language: java
install: true
addons:
  sonarcloud:
    organization: "tagbangers"
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Pjar
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.sonar/cache
